# Configuración del Sistema de Orquestación de Scraping
# Rutas relativas al directorio principal del proyecto (esdata_run)

# Modo de prueba para aislar la ejecución de scrapers
test_mode:
  enabled: false
  scraper_to_test: "Inm24" # Scraper a probar (ej. "Inm24", "CyT")

# Mapeo de nombres de CSV a códigos internos
website_mapping:
  "Inmuebles24": "Inm24"
  "casasyterrenos": "CyT"
  "Lamudi": "Lam"
  "MetrosCubicos": "Mit"
  "Propiedades": "Prop"
  "Trovit": "Tro"

# Configuración de base de datos
database:
  path: "orchestrator.db"
  backup_path: "../backups" # Subir un nivel desde esdata_run
  backup_retention_days: 30

# Configuración de directorios  
data:
  base_path: "../data" # Subir un nivel desde esdata_run
  urls_path: "urls"
  logs_path: "../logs" # Subir un nivel desde esdata_run
  temp_path: "../temp" # Subir un nivel desde esdata_run

# Configuración de scrapers
scrapers:
  path: "Scrapers"
  python_executable: "python3"
  timeout_minutes: 60 # Aumentado para robustez
  memory_limit_mb: 1024

# Configuración de ejecución
execution:
  max_parallel_scrapers: 4 # Reducido para estabilidad inicial (1 Inm24 + 3 rotativos)
  retry_delay_minutes: 30
  execution_interval_days: 15
  rate_limit_delay_seconds: 5 # Aumentado para evitar bloqueos
  max_retry_attempts: 3
  enable_auto_recovery: true
  single_url_task_per_scraper: false
  
# Configuración de monitoreo
monitoring:
  enable_metrics: true
  enable_alerts: false # Deshabilitado por ahora
  check_interval_seconds: 300

# Configuración de sitios web
websites:
  Inm24:
    priority: 1
    has_detail_scraper: true
    detail_scraper_name: "inm24_det"
    base_url: "https://inmuebles24.com"
    rate_limit_seconds: 5
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 20 # Reducido para evitar bloqueos
    
  CyT:
    priority: 2
    has_detail_scraper: false
    base_url: "https://casasyterrenos.com"
    rate_limit_seconds: 3
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Lam:
    priority: 3
    has_detail_scraper: true
    detail_scraper_name: "lam_det"
    base_url: "https://lamudi.com.mx"
    rate_limit_seconds: 4
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 25
    
  Mit:
    priority: 4
    has_detail_scraper: false
    base_url: "https://mitula.com.mx"
    rate_limit_seconds: 2
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 40
    
  Prop:
    priority: 5
    has_detail_scraper: false
    base_url: "https://propiedades.com"
    rate_limit_seconds: 3
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Tro:
    priority: 6
    has_detail_scraper: false
    base_url: "https://trovit.com.mx"
    rate_limit_seconds: 2
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 40

# Configuración de logging
logging:
  level: "INFO"
  max_file_size_mb: 50
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Variables de entorno
environment:
  debug_mode: true
  enable_profiling: false
