# Configuración del Sistema de Orquestación de Scraping - Ubuntu Linux
# Adaptado para /home/esdata/Documents/GitHub/ESDATA_710

# Configuración de base de datos
database:
  path: "orchestrator.db"  # Relativo al directorio del proyecto
  backup_path: "backups"
  backup_retention_days: 30

# Configuración de directorios  
data:
  base_path: "data"  # Relativo al directorio del proyecto
  urls_path: "urls"
  logs_path: "logs"
  temp_path: "temp"

# Configuración de scrapers
scrapers:
  path: "Scrapers"  # Relativo al directorio del proyecto
  python_executable: "/home/esdata/Documents/GitHub/Esdata_710/.venv/bin/python3"  # Usar entorno virtual con python3
  timeout_minutes: 30
  memory_limit_mb: 512

# Configuración de ejecución
execution:
  max_parallel_scrapers: 8  # Aprovechando mejor los 8 threads del Xeon
  retry_delay_minutes: 30
  execution_interval_days: 15
  rate_limit_delay_seconds: 2  # Más rápido en Linux
  max_retry_attempts: 3
  enable_auto_recovery: true
  single_url_task_per_scraper: true  # Limitar a 1 URL base por scraper; el scraper pagina internamente
  include_scrapers: ["inm24", "lam", "cyt", "mit"]
  
# Configuración de monitoreo
monitoring:
  enable_metrics: true
  enable_alerts: true
  check_interval_seconds: 300

# Configuración de sitios web
websites:
  Inm24:
    priority: 1
    has_detail_scraper: true
    base_url: "https://inmuebles24.com"
    rate_limit_seconds: 3
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  CyT:
    priority: 2
    has_detail_scraper: false
    base_url: "https://casasyterrenos.com"
    rate_limit_seconds: 2
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Lam:
    priority: 3
    has_detail_scraper: true
    base_url: "https://lamudi.com.mx"
    rate_limit_seconds: 2
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Mit:
    priority: 4
    has_detail_scraper: false
    base_url: "https://mitula.com.mx"
    rate_limit_seconds: 1
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Prop:
    priority: 5
    has_detail_scraper: false
    base_url: "https://propiedades.com"
    rate_limit_seconds: 2
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30
    
  Tro:
    priority: 6
    has_detail_scraper: false
    base_url: "https://trovit.com.mx"
    rate_limit_seconds: 1
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max_pages_per_session: 30

# Configuración de ciudades
cities:
  - code: "Gdl"
    name: "Guadalajara"
    enabled: true
  - code: "Zap" 
    name: "Zapopan"
    enabled: true
  - code: "Tlaj"
    name: "Tlajomulco"
    enabled: true
  - code: "Tlaq"
    name: "Tlaquepaque"
    enabled: true
  - code: "Ton"
    name: "Tonalá"
    enabled: true
  - code: "Salt"
    name: "El Salto"
    enabled: true

# Configuración de operaciones
operations:
  - code: "Ven"
    name: "Venta"
    enabled: true
  - code: "Ren"
    name: "Renta"
    enabled: true
  - code: "Ven-d"
    name: "Venta Departamentos"
    enabled: true
  - code: "Ven-r"
    name: "Venta Residencial"
    enabled: false

# Configuración de productos
products:
  - code: "Dep"
    name: "Departamentos"
    enabled: true
  - code: "Cas"
    name: "Casas"
    enabled: true
  - code: "Ofc"
    name: "Oficinas"
    enabled: false
  - code: "Com"
    name: "Comercial"
    enabled: false

# Configuración de datos
data_processing:
  enable_data_validation: true
  enable_duplicate_detection: true
  enable_data_cleaning: true
  export_formats: ["csv", "json"]
  compress_old_files: true  # Habilitado en Linux
  
# Configuración de backup
backup:
  enable_automated_backup: true
  retention_policy:
    daily: 7
    weekly: 4
    monthly: 3

# Configuración de seguridad
security:
  enable_rate_limiting: true
  respect_robots_txt: true
  rotate_user_agents: true
  use_proxy_rotation: false
  max_requests_per_minute: 30  # Más agresivo en Linux

# Configuración de almacenamiento SQL heterogéneo
data_storage:
  enable_sql_ingest: true              # Ingerir automáticamente cada CSV exitoso a SQLite
  table_prefix: "data_"               # Prefijo de tablas por scraper (data_cyt, data_inm24, etc.)
  normalize_column_names: true         # Normalizar nombres de columnas (lowercase, underscores)
  add_missing_columns: true            # ALTER TABLE para columnas nuevas detectadas
  chunk_size: 1000                     # Tamaño de lote para inserts masivos
  track_ingested_files: true           # Registrar archivos ingeridos y evitar duplicados
  skip_if_exists: true                 # Omitir archivo si ya está registrado
  store_metadata: true                 # Guardar definición de columnas JSON por scraper
  enforce_primary_key: false           # (Futuro) Intentar definir clave primaria si se detecta id estable
  date_detection: false                # (Futuro) Intentar castear a DATE/TIMESTAMP
  
# Configuración de logging
logging:
  level: "INFO"
  max_file_size_mb: 50
  backup_count: 3
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Variables de entorno para Ubuntu Linux
environment:
  development: false
  debug_mode: true  # Habilitado para desarrollo
  enable_profiling: false
  max_memory_usage_mb: 2048  # Más memoria disponible en Linux
